name: Build Website Image

on:
  workflow_dispatch:
  push:
    branches:
      - dev
jobs:
  prepare_tag:
    outputs:
      tag: ${{ steps.semver.outputs.next }}
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Get Next Version
        id: semver
        uses: ietf-tools/semver-action@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          branch: dev
          patchALL: true
      - name: Push tag
        id: tag_version
        uses: mathieudutour/github-tag-action@v6.2
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          custom_tag: ${{ steps.semver.outputs.next }}
          tag_prefix: ""
  deploy:
    runs-on: ubuntu-latest
    env:
      SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
    steps:
      - name: Job Start
        uses: act10ns/slack@v2
        with:
          status: starting
          channel: '#docker-build'
          message: Starting homelab.fr3d.dev build and push...

      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          ref: 'dev'
          fetch-depth: 0
      - name: Build site
        uses: Tiryoh/actions-mkdocs@v0.23.0
        with:
          mkdocs_version: 'latest' # option
          requirements: './mkdocs/requirements.txt' # option
          configfile: './mkdocs/mkdocs.yml' # option
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v5
        env:
          DOCKER_BUILDKIT: 1
        with:
          push: true
          tags: ${{ steps.semver.outputs.next }}
      - name: Notify Slack Channel of finished build
        uses: act10ns/slack@v2
        with:
          status: ${{ job.status }}
          channel: '#docker-build'
          message: BUILD COMPLETE {{env.GITHUB_REF_NAME }}
        if: always()
